var food = [
    {
        category: '牛肉',
        name: 'A5神戶和牛(肋脊)',
        price: '3800',
        serving: '10',
        img: 'img_square_6',
    },
    {
        category: '牛肉',
        name: 'A5有田和牛(菲力)',
        price: '3800',
        serving: '10',
        img: 'img_square_6',
    },
    {
        category: '牛肉',
        name: '美國頂級肋眼鍋',
        price: '780',
        serving: '9',
        img: 'img_square_6',
    },
    {
        category: '牛肉',
        name: '安格斯牛小排鍋',
        price: '680',
        serving: '9',
        img: 'img_square_6',
    },
    {
        category: '牛肉',
        name: '頂級霜降牛肉',
        price: '580',
        serving: '9',
        img: 'img_square_6',
    },
    {
        category: '牛肉',
        name: '頂級雪花牛肉',
        price: '480',
        serving: '9',
        img: 'img_square_6',
    },
    {
        category: '海鮮',
        name: '野生大龍蝦鍋',
        price: '時價',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '野生明蝦鍋',
        price: '1699',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '野生大草蝦鍋',
        price: '850',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '鯛魚鍋',
        price: '350',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '紅條石斑鍋',
        price: '550',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '日本干貝鍋',
        price: '999',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '花枝鍋',
        price: '1100',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '雪花魚捲鍋',
        price: '320',
        img: 'img_square_5',
    },
    {
        category: '海鮮',
        name: '鮭魚片鍋',
        price: '500',
        img: 'img_square_5',
    },
    {
        category: '豬肉',
        name: '梅花黑豬肉鍋',
        price: '360',
        img: 'img_square_4',
    },
    {
        category: '豬肉',
        name: '松阪豬肉鍋',
        price: '550',
        img: 'img_square_4',
    },
    {
        category: '豬肉',
        name: '匈牙利雪藏五花豚肉鍋',
        price: '680',
        img: 'img_square_4',
    },
]
