var food = [
    {
        category: '牛肉',
        name: 'A5神戶和牛(肋脊)',
        price: '3800',
        serving: '10',
        img: 'cow01',
    },
    {
        category: '牛肉',
        name: 'A5有田和牛(菲力)',
        price: '3800',
        serving: '10',
        img: 'cow02',
    },
    {
        category: '牛肉',
        name: '美國頂級肋眼鍋',
        price: '780',
        serving: '9',
        img: 'cow03',
    },
    {
        category: '牛肉',
        name: '安格斯牛小排鍋',
        price: '680',
        serving: '9',
        img: 'cow04',
    },
    {
        category: '牛肉',
        name: '頂級霜降牛肉',
        price: '580',
        serving: '9',
        img: 'cow05',
    },
    {
        category: '牛肉',
        name: '頂級雪花牛肉',
        price: '480',
        serving: '9',
        img: 'cow06',
    },
    {
        category: '海鮮',
        name: '野生大龍蝦鍋',
        price: '時價',
        img: 'seafood01',
    },
    {
        category: '海鮮',
        name: '野生明蝦鍋',
        price: '1699',
        img: 'seafood02',
    },
    {
        category: '海鮮',
        name: '野生大草蝦鍋',
        price: '850',
        img: 'seafood03',
    },
    {
        category: '海鮮',
        name: '鯛魚鍋',
        price: '350',
        img: 'seafood04',
    },
    {
        category: '海鮮',
        name: '紅條石斑鍋',
        price: '550',
        img: 'seafood05',
    },
    {
        category: '海鮮',
        name: '日本干貝鍋',
        price: '999',
        img: 'seafood06',
    },
    {
        category: '豬肉',
        name: '梅花黑豬肉鍋',
        price: '360',
        img: 'pig01',
    },
    {
        category: '豬肉',
        name: '松阪豬肉鍋',
        price: '550',
        img: 'pig02',
    },
    {
        category: '豬肉',
        name: '匈牙利雪藏五花豚肉鍋',
        price: '680',
        img: 'pig03',
    },
]
